### ISSUE TITLE
US1 - Structured Layout

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#10]
## Value proposition
As a USER
I want to a structured layout with header and footer
so that I can see important information at the top and bottom of the page without scrolling.

## Description
![Image](https://github.com/MareikeFla/community-app/assets/86231054/ab40a383-2ab5-404e-be66-34c1027d4237)

## Acceptance criteria
- [x] Page has an element on top of the page
- [x] The name of the App is displayed
- [x] Page has an element at the bottom of the page
- [x] The footer displays "Created 2024"
- [x] The content section has spacing to the left and right border
- [x] Styled according to the design specifications

## Tasks
- [x] Create branch "US1_structured-layout
- [x] Create a Layout component with children props
- [x] Create a Header component
- [x] the Header component has an element with the App title on it
- [x] Create a Footer component
- [x] Style the components according to the design specifications
- [x] In App.js wrap the Components component with the Layout component

**Comment by MerleMak** [comment]
Great job, very detailed!

I would argue this should be User story 2 tho, because our approach is to always provide value first.
If the user saw only this when going on your page, they would be confused. 
But if they saw a list of events first and in the second iteration the layout around the list of evens, it would be a lot more value added :)
