### ISSUE TITLE
US - Remove Back Button

### ISSUE THREAD

**Issue by n377i** [MareikeFla/community-app#104]
## Value proposition

As a user
I want the "Back" button to be removed from the web app 
to ensure consistent and user-friendly navigation.

## Acceptance criteria

- [ ] There is no built-in "Back" button on any page.

## Tasks

- [ ] Create branch US_remove-back-button
- [ ] Remove BackButton component
- [ ] Remove BackButton from each component in which it was used
- [ ] For cards without other buttons on top (edit/delete), change the padding-top from 3rem to 2rem
