### ISSUE TITLE
US3 - Back to top Button

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#11]
## Value proposition
As a user
I want to click a button that takes me to the top of the page
In order to navigate the page easily.

## Description
![Image](https://github.com/MareikeFla/community-app/assets/86231054/2bae6d6c-5709-44fe-ad4c-66836170c071)

## Acceptance criteria
- [x] when scrolling down a button appears on the bottom right corner of the screen
- [x] clicking the button takes me to the top of the page
- [x] Styling fits our styling criteria

## Tasks
- [x] Create branch US3_back-to-top-button
- [ ]create lib/useBackToTop.js:
- [x] create a custom hook:
  - [x] import useState
  - [x] create a state variuable called showButton. Set default value to false
  - [x] import useEffect
  - [x] create a useEffect that adds an Event Listener to the window -> if the page offset reaches a certain number, set showButton to true, else to false
  - [x] write a function that scrolls the window to the top.
  - [x] return showButton and the function

- [x] create a BackToTopButton Component
  - [x] import custom hook and destructure isShown and ScrollToTop function
  - [x] conditionally render a button on the button if showButton is true
  - [x] button should have an up arrow icon
  - [x] button should have the right ARIA properties
  - [x] button should be positioned fixed in bottom right
  - [x] the button should have a fade in animation
  - [x] Import the icon_arrow-up.svg into the component
  - [x] Place the icon inside the button element
  - [x] on clicking the button, call the ScrollToTop function

- [x] Add BackToTopButton to Layout Component
- [x] Style everything so it fits our styling criteria
