### ISSUE TITLE
DS - Improve eventform

### ISSUE THREAD

**Issue by MareikeFla** [MareikeFla/community-app#110]
## Value proposition

As a developer, I desire an event form that is user-friendly and consistent, enabling the user to create events effortlessly.

## Acceptance criteria

- start date can not be in the past
- end date can not be before start date
- end time can not be before start time
- Link is required if link description is entered
- street is required if hous number is entered
- keys for online and free of charge events will improve developers live

## Tasks

- [ ] research about use a hook to handle form data
- [ ] adapt start date so it can not be in the past
- [ ] adapt end date to be start date or after start date
- [ ] add a isOnline key to the event object
- [ ] add a isFreeOfCharge key to the object
- [ ] handle street and link URL requirements

MOVED TO A DIFFERENT US:

- long description should keep paragraphs from the event form long description field
- When long description is too long just the first 600 letters are shown followed by "...mehr" wich user can select to see the whole text
- [ ] style the long description field
- [ ] expand and collapse text
