### ISSUE TITLE
US4 - Event Detail Page

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#12]
## Value proposition
As a user
I want to click on an event
In order to see details about it

## Description
![Image](https://github.com/MareikeFla/community-app/assets/86231054/6a86675b-2ef0-42e9-80d7-6038e180f566)

## Acceptance criteria
- [x] List Items in EventList are clickable Links
- [x] clicking an event brings you to details page of this event
- [x] Event Page has a Card Component with:
  - [ ] Image
  - [x] Event Title
  - [x] description
  - [x] start & end date
  - [x] start & end time
  - [x] city/zip code/"online"
  - [x] price
  - [x] Organizer
  - [x] contact info
  - [x] Links
  - [x] category

- [x] Event Page has back button to redirect back to list
- [x] if the event is not found, user gets the info and possibility to return
- [x] matches our styling critreria

## Tasks
- [x] create branch US4_events-details-page
- [x] In the EventList component, add Link Component, linking to /events/event.id
- [x] update mock data array with missing data
- [x] create /events/[id]/index.js
- [x] create EventDetail component (prop: event)
- [x] create a BackButton component:
  - [x] Link has a left facing Arrow Icon as content
  - [x] add a Link redirecting to Homepage
  - [x] add ARIA properties to link
- [x] Import useRouter
- [x] use router.query.id and find method to get the right Event from the events array
- [x] write early return statement for the case there is no event ("event not found")
- [x] write jsx to show the needed information
- [x] match our styling critreria

**Comment by Miriam-Voelkl** [comment]
very clear and concise US, well done! ✨
