### ISSUE TITLE
DS - protect user api route

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#129]
## Value proposition
As a developer
I want to have safe api routes
In order to protect the data of my users

## Acceptance criteria
- [ ] api/comments, /api/user and /api/user/[id] are not accessible from the browsers url bar

## Tasks
- [ ] Create new branch DS_protect-user-api
- [ ] in /api/auth/[...nextauth].js save authOptions in variable and export export NextAuth(authOptions)
- [ ] in  /api/user and /api/user/[id], and api/comments import getServerSessions and authOptions and rewrite requests following [this example](https://github.com/NikRoe/next-auth-pony-demo/pull/1/files#diff-e0861d63eed5eacaa4b7c51e620e1da44a7579bccf244d96b26efb5d93c6b8a3)
- [ ]
