### ISSUE TITLE
US7 - Create Event

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#13]
## Value proposition
As a User
I want to create events
so other people can see them

## Description
![Image](https://github.com/MareikeFla/community-app/assets/86231054/dbc0c79d-59c9-4807-93f5-045ed481ea43)
![Image](https://github.com/MareikeFla/community-app/assets/86231054/23ccb506-c8f7-4f75-81fe-4b18b0582fdd)

## Acceptance criteria
- [x] there is a clickable element that redirects to the create event page
- [x] on the create event page, there is:
  - [x] a clickable element to get back to the homepage
  - [x] a form element to enter the needed information for event creation
  - [x] a button to submit the created event
  - [x] a button to cancel the creation
- [x] an error message if something went wrong
- [x] successfully creating an element redirects you to the details Page of the created element
- [x] create event button is not shon on /new page
- [x] styling according to our criteria

## Tasks
- [x] create branch US7_create-event
- [x] create pages/events/new.js
- [x] create AddEventButton that pont to pages/events/new.js
- [x] add AddEventButton to  Header Component
- [x] create NewEventCard component
  - [x] add BackButton component
  - [x] add an Element instructing user what to do
  - [x] create EventForm component
- [x] EventForm component:
  - [x] takes a function as prop
  - [x] add label and input fields for every needed information field. connect them with id/htmlFor
  - [x] required fields:
    - [x] eventName
    - [x] category
    - [x] startDate
    - [x] location
      - [ ] street
      - [ ] number
      - [ ] city
      - [ ] zip
    - [ ] cost -> not shown if empty, checkbox for free events
    - [ ] organization
    - [ ] contactDetails
    - [x] shortDescription
    - [ ] longDescription
  - [ ] non required:
    - [x] imageURL
    - [ ] endDate
    - [x] start & endTime
    - [x] LinkURL 
  - [ ] add button with type="submit"
  - [ ] add abort button (links to homepage)
  - [x] add onSubmit function to form element
- [x] onSubmit function in form element:
  - [ ] prevents default functionality
  - [x] gets FormData
  - [ ] executes handleData function with FormData as argument
  - [ ] resets input fields after submission
  - [x] points to created event details page after submission
- [ ] in /pages/event/new.js:
- [ ] hide NewEventButton
- [ ] write async AddNewEvent  function:
  - [ ] takes data as argument
  - [ ] makes a POST request with fetch method
  - [ ] add error handling
- [x] pass AddNewEvent function to app as handleData to EventForm component
- [x] in api/events/index.js, write the corresponding POST request with error handling

**Comment by MerleMak** [comment]
Nice job! Very detailed, really nice!
Do you want to add the image link and dynamically import it via the link?
The users would have to watch out then to only use photos without copyright. You could implement a proper image upload, but you would need to implement a library for that like cloudinary.
That should be it's own userstory though. 

Please answer here in the comments ↓

**Comment by MareikeFla** [comment]
Hi, we are planing a image upload and will move that to another user story :)
