### ISSUE TITLE
US - delete comments and replies

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#130]
## Value proposition
As a User
I want to delete comments I left
In order to have control over my data

## Description
![Image](https://github.com/MareikeFla/community-app/assets/86231054/af22a5e7-1c11-4115-a092-3082f007030b)

## Acceptance criteria
- [x] commts and replies show a delete button for logged in creator when in "edit mode"
- [ ] if user clicks it, a modal pops up asking if user is sure to delete comment
- [ ] confirming deletes comment and/or reply from database
- [x] if comment with replies is deleted, the replies to that comment is deleted as well
- [x] App design matches our design criteria

## Tasks
- [x] Create new branch US_delete-comments
- [x] add Delete button to CommentForm component
- [x] conditionally render it so it only shows if logged in user is comment/reply owner
- [x] add delete request to useData hook and import it to Comment component
- [x] add api route for deleting comments and potetial replies
- [x] Style new elements according our styling criteria
