### ISSUE TITLE
DS - fix login issues

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#133]
## Value proposition
As a developer
I want to have a working sign up and login process
In order to maximize the user experience

## Acceptance criteria
- [ ] changing tabs does not log user out
- [ ] the session time is longer than it is now
- [ ] events without event owner are not editable

## Tasks
- [ ] Create new branch DS_fix-login-issues
- [ ] find out what is going with the session tokens and fix it :)
- [ ] refactor edit restrictions in DetailsCard component
- [ ] add createdBy key with value to all events
