### ISSUE TITLE
US5 - Database Setup

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#14]
## Value proposition
As a Developer
I want to set up a Databease
In order to have a place to store the events

## Acceptance criteria
- [x] Mongo DB Collection is set up
- [x] the Collection is connected to the API using mongoose
- [x] the Event Schema is Set Up
- [x] the skeletons for the api routes are set up

## Tasks
- [x] create branch US5_database-setup
- [x] Set up MongoDB:
  - [x] Create a collection with Atlas
  - [x] transfer Mock data from /lib to the collection
- [x] Set Up db connection
  - [x] create .env.local and insert MongoDB_URI
  - [x] create /db and /db/models
  - [x] create a connect.js in /db and paste the connectDB function from our Sessions
  - [x] Create Event.js and set up the Schema
- [x] Set Up API
  - [x] create pages/api/events
  - [x] create index.js
    - [x] import dbConnect funtion and Event Schema
    - [x] write handler function
    - [x] await db connect
  - [x] create [id]/index.js
    - [x] import dbConnect funtion and Event Schema
    - [x] write handler function
    - [x] await db connect

**Comment by MerleMak** [comment]
Very nice job!
When there is no description (skibble,wireframe) you can leave out this point entirely :)
approved ✅
