### ISSUE TITLE
US6 - API connection

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#15]
## Value proposition
As a developer
I want to fetch the data from a database
so the user can acces it from anywhere

## Acceptance criteria
- [ ] Data is fetched from database

## Tasks
- [x] create branch US6_api-connection
- [x] in api/events/index.js
  - [x] add get request to handler function using mongoose find method
- [x] in api/events/[id]/index.js
  - [x] add get request to handler function using mongoose findById method
- [x] in _app.js:
  - [x] import SWRconfig
  - [x] write a fetcher function outside the component
  - [x] wrap the Component component with the SWRConfig component and gve the fetcher function as value
- [x] in pages/index.js:
  - [x] fetch the events array from /api/events using useSWR hook
  - [x] destructure data, error and isLoading from the hook
  - [x] rename data to events
  - [x] set up early return statements for error and isLoading
  - [x] delete import of mock data array
  - [x] pass fetched data to EventList Component
- [x] in pages/events/[id].js:
  - [x] fetch the individual event data using useSWR and useRouter hooks
  - [x] destructure data, error and isLoading from the hook
  - [x] rename data to event
  - [x] set up early return statements for error and isLoading
  - [x]  delete import of mock data array and array itself
  - [x] pass fetched data to EventDetail Component

**Comment by MerleMak** [comment]
looks complete to me! 
Nice job :)
