### ISSUE TITLE
Delete & Edit images with cloudinary

### ISSUE THREAD

**Issue by MareikeFla** [MareikeFla/community-app#154]
## Value proposition

As a user creating events I want to edit or delete the events picture to react on changes or mistakes. 

## Acceptance criteria

- [ ] When user editing an event the event picture is shown as a preview. picture can be deleted and replaced by another picture
- [ ] Picture is deleted from cloudinary database when user is deleting or replacing it.

## Tasks

- [ ] Create branch US_deleteAndEditEventImages

eventDetail.js
- [ ] adapt Event Form to show image preview when editing an image with a picture (Like it is shown when creating an image)
- [ ] research how to delete an image from our cloudinary account and add functionality to the buttons for deleting an image and replacing an image
