### ISSUE TITLE
US8 - Edit Events

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#16]
## Value proposition
As a User
I want to edit events
In order to react to changes

## Description
- Scribble / design or text
- Precise, no unnecessary information

## Acceptance criteria
- [ ] on details page, there is a clickable element that brings user to edit page
- [ ] Edit page has a form with current data as default value
- [ ] Edit page has a button to abort editing
- [ ] Edit Page has a button to save changes
- [ ] there is a confirmation button before saving changes
- [ ] confirming changes brings user back to details page of this event

## Tasks
- [ ] create pages/events/edit.js
- [ ] add Header Component
- [ ] create EditEventCard component
  - [ ] add HomePageLink component
  - [ ] add an Element instructing user what to do
  - [ ] add EventForm component
  - [ ] pass the event as prop to the EventForm component
  - [ ] write async EditEvent  function:
  - [ ] takes data as argument
  - [ ] makes a PUT request with fetch method
  - [ ] has error handling
- [ ] pass EditEvent function to app as handleData to EventForm component
- [ ] in api/events/[id].js, write the corresponding PUT request with error handling
- [ ] EventForm component: 
 - [ ] give event as prop to component wit an empty Object as default Value
 - [ ] add defaultValue to each input element using the event prop
