### ISSUE TITLE
US - Readme

### ISSUE THREAD

**Issue by n377i** [MareikeFla/community-app#169]
## Value proposition
As a user
I want to access a comprehensive Readme file for the app
so that I can understand its purpose, features, and technical details.

## Acceptance criteria
- [ ] Short description of the use case of the app (mentioning the target group if you have a specific one)
- [ ] Overview of the main features
- [ ] Tech stack
- [ ] Introduction of the Dev Team
- [ ] Hero Image (e.g. Readaholic and Carbon and Lactate App)
- [ ] Demo Images/Video
- [ ] Local Development Guide

### Inspiration
- [Die Plant Care App](https://github.com/Fabi911/Capstone_Plant_Care/blob/main/README.md)
- [Pocket Pets App](https://github.com/Krischan-Klug/pocket-pets/blob/main/README.md) 
- [Carbon and Lactate App](https://github.com/miriamhaenle/capstone-project/blob/master/README.md) 
- [Readaholic](https://github.com/mbosselmann/capstone-project/blob/main/README.md) 

## Tasks
- [ ] Create a new branch "US_readme"
- [ ] Edit the README.md according to the acceptance criteria
