### ISSUE TITLE
US9 - Delete Event

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#17]
## Value proposition
As a user
I would like to be able to delete events
in case they are canceled.

## Description

![Image](https://github.com/MareikeFla/community-app/assets/148346025/d2486ba9-3dd7-4d86-a41a-d39741ccf09e)

## Acceptance criteria
- [x] Details Page has a clickable Element to delete events
- [x] deleting event redirects to homepage

## Tasks
- [x] Create DeleteEventButton component
- [x] component takes an event id as prop
- [x] write an async funtion  that handles the DELETE method using the fetch method and the event id
- [x] the function also redirects to the homepage
- [x] add a button, onclick call the delete function
- [x] in /api/events/[id].js, add the DELETE request to the handler function

- [x] Add the DeleteEventButton to the event details component

**Comment by NikRoe** [comment]
Hi there,

this looks really nice, but I am missing one point in your AC.

This task:
> the function also redirects to the homepage

should also be described in the Acceptance Criteria.

Please add this to the AC and then you can consider this user story as approved.
