### ISSUE TITLE
US - info pages

### ISSUE THREAD

**Issue by n377i** [MareikeFla/community-app#170]
## Value proposition
As a user
I want to access Imprint, Privacy Policy, and About pages of the app
so that I can easily find information about the app's legal aspects and learn more about its purpose and creators.

## Description
![Image](https://github.com/MareikeFla/community-app/assets/86231054/20e96704-9989-4d65-a6a3-8e8315545d56)

## Acceptance criteria
- [ ] The footer contains three links: "Impressum", "Datenschutz", and "About".
- [ ] These links route to corresponding pages with appropriate content.

## Tasks
- [ ] Create new branch "US_info-pages".
- [ ] Create components Imprint.js, PrivacyPolicy.js and About.js and fill them with appropriate content.
- [ ] Create corresponding page routes in the pages directory.
- [ ] Link these pages in the footer under "Impressum", "Datenschutz", and "About".
- [ ] Style them according to our design specifications.
