### ISSUE TITLE
DS - refactoring #2

### ISSUE THREAD

**Issue by n377i** [MareikeFla/community-app#171]
## Value proposition
As a developer
I want to refactor my code
so that the App works as intended

## Acceptance criteria
- [ ] If a link is added without a link description when creating an event, show “Mehr Informationen” as the link name on the event detail page by default. 
- [ ] If an event lasts several days, add the end date of the event to the event preview so that the user is no longer confused by the fact that a past date is displayed.
- [ ] The Buttons in the home page welcome header need to be displayed one below the other when the screen is to small.

## Tasks
- [ ] Create a new branch "DS_refactoring-2".
- [ ] EventDetail component: Add  a condition to check if a link description is present. If not, display "Mehr Informationen" instead.
- [ ] Rename the label "Weitere Infos" to "Link".
- [ ] EventPreview component: Pass the end date as a prop. Add a condition to check whether an end date exists. If it does, show it with a dash after the start date.
- [ ] WelcomeCard.styled.js: Add "flex-wrap: wrap;" to the LinksContainer.
