### ISSUE TITLE
US - Filter Search

### ISSUE THREAD

**Issue by MareikeFla** [MareikeFla/community-app#173]
## Value proposition

As a user I want to filter search results for accessibility and category to adapt the result to my needs. 

## Description

![Image](https://github.com/MareikeFla/community-app/assets/148346025/e72dfe64-8a37-44a5-bcee-839ef9d78eb8)

## Acceptance criteria

- [ ] User can filter events/search result for a11y tags and category tags
- [ ] By clicking the related icon/tag the filter will be applied
- [ ] clicking again remove the filter
- [ ] when a filter is shown an option is visible to reset all filters
- [ ] clicking a filter option without performing a search will filter all events

## Tasks

- [ ] render a11y icons and category tags on search card
- [ ] save filter status in a state and filter events based on the chosen filter
- [ ] create a reset button to reset filter
