### ISSUE TITLE
US - Filter Events

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#18]
## Value proposition
As a User
I want to filter the shown events
In order to only see what i am interested in

## Description

![Image](https://github.com/MareikeFla/community-app/assets/148692082/36040fa3-6e12-4e66-acc6-2901f3e3eb84)

## Acceptance criteria
- [x] There are 4 clickable elements on the homepage
- [x] each element stands for one category
- [x] each card shows how many events there are for this category
- [x] clicking on an element filters the data for said element
- [x] styled according to design

## Tasks
/pages/index.js:
- [x] create array called mainCategories. The array has our four main categories as items
- [x] create a CategoryContainer component and pass down the mainCategories array as prop
- [x] create CategoryList component and add it to CategoryContainer component
- [x] create a CategoryCard component
- [x] in CategoryList map over mainCategories and render a CategoryCard for each entry
  - [x] each CategoryCard gets the amount of events as prop (use filter method and "array".length)
- [x] each CategoryCard is a Link component that point to events/`${category}`
- [x] create events/[category]/index.js
  - [x] use useRouter to get category 
  - [x] use useSWR and query.category to fetch data with given category
  - [x] add BackButton component
  - [x] add EventList component and pass down fetched data
- [x] create /api/event/[category]/index.js
  - [x] write get request to get filtered data by category
- [x] add CategoryContainer to /index.js

**Comment by NikRoe** [comment]
Nicely done
