### ISSUE TITLE
US - Google Login

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#184]
## Value proposition
As a User
I want to log into the app with my google account
In order to use it without a github account

## Acceptance criteria
- [ ] Google Login is available in login screen

## Tasks
- [ ] Create new branch US_google-login
- [ ] Set Up Google Account
- [ ] add ID and secret to env.local
- [ ] add google provider to nextauth file
