### ISSUE TITLE
US14 - Search Functionality

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#19]
## Value proposition
As a User
I want to be able to search for events
In order to see exactly what I am interested in

## Description

![Image](https://github.com/MareikeFla/community-app/assets/148692082/25bdc020-1fed-4ec5-bc19-005202cb040b)

## Acceptance criteria
- [x] Header has a clickable search icon
- [x] clicking it brings you to a search page
- [ ] on the search page, there are:
  - [x] a button to navigate back
  - [ ] a header: "Wonach suchst du?"
  - [ ] an input field witch Icon an Placeholder Text
- [ ] If there are no results, a message is shown
- [ ] Search results are clickable and bring you to Details Page

## Tasks
- [x] Create branch US_search-events
- [x] Create a create a SearchIcon component
  - [x] Clicking it brings you to /search page
- [x] /search page:
  - [ ] submitting the search renders results with EventList compinent
  - [ ] search page renders found events with EventList component
  - [ ] if there are no results, a message is rendered
- [ ] Create search index in Atlas
  - [ ] in your Atlas Account, got to Tab "search" and create search index for events collection
- [ ] create api Endpoint for the pipeline (research how to do that :))
- [ ] enable fuzzy search
- [ ] link search input and api endpoint
