### ISSUE TITLE
US13 - Navigation

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#20]
## Value proposition
As a user
I want be able to to open a menu
in order to navigate the pages easily.

## Description
![Image](https://github.com/MareikeFla/community-app/assets/86231054/c7a5be00-2981-40e9-9fa5-7f831c3003c3)
![Image](https://github.com/MareikeFla/community-app/assets/86231054/482e6373-1eef-4d9e-91bd-cd889fdfda97)

## Acceptance criteria
- [x] There is a burger menu icon in the top left corner of the header.
- [x] Clicking on the menu icon
    - [x] the bars change smoothly into an X shape.
    - [x] the navigation menu moves in from the left and fills the entire screen.
- [x] In the center it contains links to the major pages.
- [x] Clicking the X, the navigation menu moves to the left, out of the screen again.
- [x] The styling corresponds to our design specifications.

## Tasks
- [x] Create a new branch "US13_navigation“.
- [x] Create component „Navigation“.
- [x] Add and style the menu icon to display three horizontal bars using spans.
- [x] Add a list of menu items (for now that will be „Home“ and „Event erstellen“) and link the relevant pages.
- [x] Add styling according to our design.
- [x] Implement state management to toggle the menu open and close states.
- [x] Pass the isOpen state as a prop to the Icon and Menu.
- [x] Position the menu off-screen to the left initially.
- [x] Animate the transformation of the menu icon and the movement of the menu with transition and transform properties.
- [x] Integrate Navigation component into Layout component.
