### ISSUE TITLE
US - Map integration

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#21]
## Value proposition
As a User
I want to see the events location on a map
In order to have a visualization where it takes place

## Description

![Image](https://github.com/MareikeFla/community-app/assets/148692082/7334d01a-0929-4bbb-86f0-7763e6c147b7)

## Acceptance criteria
- [x] On the Details Page, there is a Map component
- [x] on the map, the location of the event ist represented by a pin
- [ ] if there is no valid Adress, a message is shown to the user
- [x] it is styled as seen in design our design

## Tasks
- [x] create branch US_map-integration
- [x] import leaflet and react leaflet
- [x] create DetailMap component
- [x] integrate leaflet as per its documentation
- [x] if there is a valid adress, render DetailMap in EventDetail
- [ ] if not, render MessageCard component with appropriate message
- [x] style the map component

**Comment by MerleMak** [comment]
the example text hahahahah

when the user creates an event, is the map (with the pin) generated based on the adress that the user puts in?

**Comment by MerleMak** [comment]
What is the user puts in an invalid adress ? 😏

**Comment by Bruno0221** [comment]
In our Data, we hat latitude and longitude for now. We don't know how to geolocate an adress  when creating a new adress... yet...

**Comment by Bruno0221** [comment]
I updated the US with the case that we don't have a valid address
