### ISSUE TITLE
US10 - Confirmation Modal

### ISSUE THREAD

**Issue by MareikeFla** [MareikeFla/community-app#27]
## Value proposition

As a user, I want to be able to confirm my action in a modal window when  deleting  an event, before the action is finalized, to prevent accidental deleting

## Description

![Image](https://github.com/MareikeFla/community-app/assets/148346025/1892a224-29c4-4f47-bff6-a272435cd892)

## Acceptance criteria

- [x] ESC will close the modal

event/[id]

- When clicking the delete button a modal shows up
   - [x]  text: "Dieses Event wirklich löschen?"
   - [x]  button1: "Abbrechen" -> Event is not deleted, user can see events details page
   - [x]  button2: "Löschen" -> Event is deleted and user is redirected to the event list

## Tasks
- [x] create branch US9_confirmation_modal
- [x] create ConfirmationModal component
   - [x] props:   { message: "", textButtonClose: "", textButtonConfirm: "", onClose, onConfirm }

   - [x] return dialog element including
      - [ ] message 
      - [ ] and two buttons showing the button texts 
      - [ ] and calling onClose/onConfirm when clicked

- [ ] add modalInfo and setModalInfo useState with default value { message: "", textButtonClose: "", textButtonConfirm: "", onClose, onConfirm}
- [ ] import useRef and set a hook
   - [x] create function openModal (props: message: "", textButtonClose: "", textButtonConfirm: "",  onConfirm)
   - [x] calling showModal on the current ref
   - [ ] calling setModalInfo setting the infos accrodingly and onClose call close on the current useRef hook
- [ ] pass modalInfo and, showModal

- [x] add ConfirmationModal to  /events/[id]
- [x] on click dete button call showModal 
   - [ ] with accordingly infos
   - [ ] move current button functionality to delete to onConfirm

- [ ] style according our styling criteria

**Comment by NikRoe** [comment]
Well done 👍

**Comment by MareikeFla** [comment]
I cut down this user Story to create the component, implement functionallity and show a modal just on clicking the delete button, because our form for creating and editing is not ready yet. 
Created a new user story to add modals for saving/editing events
