### ISSUE TITLE
US11 - Welcome Card

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#30]
## Value proposition
As a User
I want to be greeted when I visit the Homepage
In order to feel welcomed and know what to do

## Description

![Image](https://github.com/MareikeFla/community-app/assets/148692082/a1643933-438a-46c7-b511-f0e018381a8e)

## Acceptance criteria
- [x] A Welcome Message is shown when user opens the Homepage
- [x] An illustration is shown
- [x] A cta Button is shown. It points to "create events" for now
- [x] it is styled to our standart

## Tasks
- [x] Create new branch US_welcome-card
- [x] create a WelcomeCard component. It has:
  - [x] a h1 with a greeting message
  - [x] an  Illustration as Background image
  - [x] a Link Component that redirects to /events/new
- [x] Add WelcomeCard to /index.js
- [x] Style new elements according our styling criteria

**Comment by Bruno0221** [comment]
Thanks for the feedback NikRoe! I changed the Button to a Link component and updated the wireframe :)

**Comment by NikRoe** [comment]
Nice! Approved ✅
