### ISSUE TITLE
US15 - Sort Event List

### ISSUE THREAD

**Issue by MareikeFla** [MareikeFla/community-app#36]
## Value proposition

As a user searching for events to attend,
I want the event list to automatically prioritize and display upcoming events at the top,
So that I can easily find and join events that are happening next, enhancing my experience and ensuring I don't miss out on timely opportunities.

## Acceptance criteria

- [x] All event lists/ main and category lists are sorted by start date ASC
- [x] event list as a search result dont

## Tasks
- [x] Create branch
- [x] add isSorted prop with default false to EventList component
- [x] Sort the incoming array in EventList component by start date before mapping it if isSorted is false
