### ISSUE TITLE
To DO: Image upload with cloudinary

### ISSUE THREAD

**Issue by MareikeFla** [MareikeFla/community-app#37]
##AC

- [ ] user can chose a picture (jpg png) to upload in the event form 
- [ ] the user must confirm that he is allowed to use the image
- [ ] user can upload the image and gets a notification about status
- [ ] 

##Tasks 
- [ ] Create cludinary account
   - [ ] Create cloud with name eventImages
   - [ ] Set upload preset to unassigned

db/models/Event.js
-  Change Event Schema image key
    -  image: {
         type: new Schema({
           width: Number,
           height: Number,
           url: String,
           alt: String,
      })

- [ ] Add NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=eventImages to env.local and adapt env.local.example
- [ ] Also add key and value to the vercel environment variables 

Upload image to cloudinary

- [ ] create lib/upload.js
   - [ ] variables CLOUD_NAME (cloud name from env.local) and [UPLOAD_PRESET (?)](https://cloudinary.com/documentation/image_upload_api_reference)
   - [ ] write async upload function (props: file) 
      - [ ] create a [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData?retiredLocale=de) object named imageData
   - [ ] and append file and upload preset 
   - [ ] await fetch response from [`https://api.cloudinary.com/v1_1/${CLOUD_NAME}/image/upload`](https://cloudinary.com/documentation/image_upload_api_reference)
      - [ ] with method POST and imageData as body
   - [ ] deconstructere and return url, width, height from response

Saving imageInfos mongoDB

event form
- [ ] add input field (and label) with name "image" and type file that accepts .jpg and .png
- [ ] and text field with label image description/alt text (?)
- [ ] and checkbox where user has to confirm he is allowed to use the image (for submit: required to be checked if a file is selected)

- [ ] adapt on submit function
   - [ ]  call the upload function with the file as a prop (event.target.image.files[0]) and await response
   - [ ] append the uploads function return values to the POST

**Comment by MerleMak** [comment]
i think nothing can go wrong with a user story like that!!

**Comment by MareikeFla** [comment]
😂 I felt like if I write it down that specific while trying to understand how it works will prevent me from being lost when coding next week 😂
