### ISSUE TITLE
US - Favicon & page title

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#38]
## Value proposition
As a User
I want to I want the App to have a favicon and pagetitle
So I can find the app in my browsers tab bar

## Acceptance criteria
- [ ] Tab bar shows favicon
- [ ] Tab bar shows page title

## Tasks
- [ ] Create new branch US_favicon-page-title
- [ ] add favicon.ico to /public
- [ ] in _documentt.js, add a title element to the Head component
