### ISSUE TITLE
US - Tooltips

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#39]
## Value proposition
As a User
I want to see a tooltip when I hover over an icon
In order to know what it is about if I don't understand the icon

## Description

![Image](https://github.com/MareikeFla/community-app/assets/148692082/c08c41af-9f78-4804-9d85-2628986c0088)

## Acceptance criteria
- [ ] hovering over an icon for about .5 seconds opens a tooltip element
- [ ] the element contains a short text explaining the bavaviour

## Tasks
- [ ] Create new branch US_tooltips
- [ ] create a Tooltip component
- [ ] the component takes two props: children and text
- [ ] create a TooltipContainer styled component and give it position relative
- [ ] TooltipContainer:
  - [ ] has the chlidren prop inside
  - [ ] has a TooltipText styled component with position absolute. it renders a span element with the text prop
  - [ ] by default, ToolTiptext has opacity 0, on hover it fades in 
- [ ] style the components according to design
- [ ] wrap the icons with the tooltip components
