### ISSUE TITLE
US - Comments

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#40]
## Value proposition
As a User
I want to leave comments on Events
In order to share my thoughts with the universe

## Description

![Image](https://github.com/MareikeFla/community-app/assets/148692082/4660bdb1-a45f-4cd0-aea6-b537ddbf6ab2)

![Image](https://github.com/MareikeFla/community-app/assets/148692082/18498251-865a-426f-bd21-e4bcae04df49)

## Acceptance criteria
- [ ] Event Details page has an Input field with a submit button
- [ ] clicking the Button submits the comment and it gets rendered on the page
- [ ] there is a header element that informs user about the number of comments

## Tasks
- [ ] Create new branch US_create-comments
- [ ] create a comments collection in mongodb
- [ ] add comments collection per object id to events collection
- [ ] create Comment schema and model
- [ ] in get requests, populate events with comments
- [ ] create Comments component (prop: id)
- [ ] fetch comments from db using useSWR and the id
- [ ] create CommentsList component(prop: comments)
- [ ] Create Comment component
- [ ] in CommentList, map ofer comments and create a Comment component for each comment
- [ ] add a header informing about the number of comments
- [ ] create CommentForm component
- [ ] add input field and button to a form element
- [ ] submitting the form writes new comment into db
- [ ] add heading, CommentList and CommentForm to Comments
- [ ] Style new elements according our styling criteria
