### ISSUE TITLE
US Loading - Animation

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#41]
## Value proposition
As a User
I want to see an animation when data is loading
so I know that I have to wait for data to show up

## Acceptance criteria
- [ ] When data is loading an animation is visible

## Tasks
- [ ] Create new branch US_loading-animation
- [ ] add an animation to the Loading component
- [ ] Style new elements according our styling criteria

**Comment by Bruno0221** [comment]
changed, thank you :)
