### ISSUE TITLE
US Like Comments

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#43]
## Value proposition
As a User
I want to be able to like comments
In order to show my agreement of the things being said

## Description
- Scribble / design or text
- Precise, no unnecessary information

## Acceptance criteria
- [ ] comments have a linke button
- [ ] clicking it will give a visual representation
- [ ]

## Tasks
- [ ] Create new branch USx-userStorieName
- [ ] Style new elements according our styling criteria
- [ ]
