### ISSUE TITLE
US - Show category in event preview

### ISSUE THREAD

**Issue by MareikeFla** [MareikeFla/community-app#45]
## Value proposition

As a user looking for events I can attend, I want to see the events category in the event preview
so I can decide better if an event is interesting for me.

## Description

![Image](https://github.com/MareikeFla/community-app/assets/148346025/2e5e7bc9-1ba1-4cc2-87c6-f85e61ef643d)

## Acceptance criteria

- [ ] Events category is shown on events preview card

## Tasks

- [ ] Create branch US_category-in-preview
- [ ] Adapt EventPreview component to render category and style it according our styling guide
