### ISSUE TITLE
US - Geocode location on event creation

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#49]
## Value proposition
As a <user/role>
I want to <feature/goal>
In order to <benefit/purpose>

## Description
- Scribble / design or text
- Precise, no unnecessary information

## Acceptance criteria
- [ ] App design matches our design criteria
- [ ]

## Tasks
- [ ] Create new branch USx-userStorieName
- [ ] Style new elements according our styling criteria
- [ ]

**Comment by MerleMak** [comment]
please adjust the description and the branchname :))

**Comment by marcel-epp** [comment]
The first two points in the acceptance criteria could be one point?

- [ ] when entering an address while creating a new event
- [ ] a dropdown appears, showing possible locations

to:

- [ ] when entering an address while creating a new event a dropdown appears, showing possible locations
