### ISSUE TITLE
US - Show time since comment

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#52]
## Value proposition
As a user
I want to see when a comment was made
In order to knwo if it is new or old

## Description

![Image](https://github.com/MareikeFla/community-app/assets/148692082/c6ba0234-c112-4ad0-ac57-88f1dbe42aec)

## Acceptance criteria
- [ ] next to user name there is an element showing how much time has past since commenting
- [ ] App design matches our design criteria

## Tasks
- [ ] Create new branch US_time-since-comment
- [ ] add creation date of comment in data model
- [ ] to Comment component, add an element calculating time difference between time of creation and current time
- [ ] Style new elements according our styling criteria
