### ISSUE TITLE
US - Click Logo for return to main page

### ISSUE THREAD

**Issue by MareikeFla** [MareikeFla/community-app#59]
## Value proposition
As a user navigating through the app, I want to have a short link that brings me to the main page 
so that I can easily and quickly return to the homepage at any time, enhancing my user experience by providing a straightforward way to start over or redirect my search without having to navigate through multiple pages or use the back button extensively.

## Acceptance criteria
- [x] clicking the Pin&Join logo will user redirect to the main page

## Tasks
- [x] Create new branch US_Header-Link
- [x] Add a link to the pin&join logo directing to "/"
