### ISSUE TITLE
US - Category Headers

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#63]
## Value proposition
As a User
I want to see a a header element on each category page
In order to have visual guidance on where I am on the page

## Description

![Image](https://github.com/MareikeFla/community-app/assets/148692082/c375b819-522e-4c7f-a490-124a3f075ff1)

## Acceptance criteria
- [ ] Each category page has a header card
- [ ] the card consists of a back button, an image representing the category and a title

## Tasks
- [ ] Create new branch US-category-header
- [ ] create CategoryHeader component
- [ ] add BackButton to component
- [ ] add the categories image as background image to the component
- [ ] add a the category title
- [ ] Style new elements according our styling criteria
