### ISSUE TITLE
US-1/Event List

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#7]
## Value proposition
As a user
I want a list of events 
so that I can easily browse through upcoming events  and decide which ones might interest me.

## Description
- Scribble / design or text
- Precise, no unnecessary information

## Acceptance criteria
- [ ] At the top of the page you can see a header with the app title.
- [ ] Each event is shown in an individual card.
- [ ] The cards are shown as a list
- [ ] Every card has to show title, date, time, short description and place of the event
- [ ] The list scrolls vertically
- [ ] The design fits our standard criteria we agreed on

## Tasks
- [ ] Create branch feature/US1eventList
- [ ] Create lib/events.js
- [ ] Create mock array events for development purposes
- [ ] create object on it including keys title, dateStart, dateEnde, timeStart, timeEnd, zip, city, isOnline, costs
- [ ] Create Header component
- [ ] Show app name in the Header
- [ ] Create EventPreview (props: event) component and return  Title, date, time, zip, city (or “online” if isOnline is true) costs 
- [ ] index.js: 
- show Header on top of the page, 
- map events array and return one eventPreview for every event on the  array
