### ISSUE TITLE
Add event list heading on main page

### ISSUE THREAD

**Issue by MareikeFla** [MareikeFla/community-app#71]
## Value proposition
As a user, I want the event list on the main page to have a heading 
so that I can easily distinguish it from other content and quickly find upcoming events of interest.

## Acceptance criteria

- [x] Event List on the main page has a heading saying "Aktuelle Events"

## Tasks

- [x] Create branch US_event-list-heading
- [x] Add a a h2 to the event list
