### ISSUE TITLE
DS - Refactoring

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#78]
## Value proposition
As a Developer
I want to refactor my code
In order to fix smaller issues that I discovered after pushing it

## Acceptance criteria
- [ ] Images in CategoryCard Component have the needed resolution
- [ ] Footer does not overflow 
- [ ] map component does not overlay navigation
- [ ] the Back to top Buttin uses Next Image component instead of img element
- [ ] the custom map marker has a shadow

## Tasks
- [ ] Create new branch DS-refactoring
- [ ] CategoryCard: add layout: fill to Image component
- [ ] Footer: add "padding: 1.375rem 1rem;" and  "width: 100%"
- [ ] Map: add "z-index: 0;" to map
- [ ] Map Marker: add shadow png to custom marker element
- [ ] BackButton: change img to next Image component
