### ISSUE TITLE
DS - Overhaul data fetching

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#79]
## Value proposition
As a Developer
I want to only fetch the data I need and where I need it
In order to optimize my Apps performance

## Acceptance criteria
- [ ] All data is only fetched once
- [ ] it is fetched in the appropriate location to be shared between components
- [ ] it is only fetched, if the right url is entered

## Tasks
- [ ] Create new branch DS_overhaul-data-fetching
- [ ] check all places where data is fetched
  - [ ] if same data is fetched in multiple places, consolidate it inthe appropriate place
  - [ ] check if fetching data can be prevented by other methods (e.g. filtering fetched data for categories)
- [ ] implement a check for data fetching in dynamic routes
