### ISSUE TITLE
US - Category Colors

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#81]
## Value proposition
As a User
I want each category being represented by an individual color
In order to easily distinguish between them

## Description

![Image](https://github.com/MareikeFla/community-app/assets/148692082/51dcac12-ddc9-475b-ae4d-0a219e7d389a)

## Acceptance criteria
- [ ] each category tag has its own color as deignated in our design file

## Tasks
- [ ] Create new branch US_category-colors
- [ ] add color codes to items in categories collection as categoryColor
- [ ] rewrite event data collection so categories are stored as a reference to the categories collection
- [ ] rewrite api routes to match new data structure
- [ ] pass category color as custom prop to CategoryTag components background-color
- [ ] Style new elements according our styling criteria
