### ISSUE TITLE
DS - Refactor Modal in useContext hook

### ISSUE THREAD

**Issue by MareikeFla** [MareikeFla/community-app#82]
## Value proposition

As a software developer,
I want to design and implement components that are highly reusable,
so that I can efficiently apply the same components across different parts of the application for similar use cases, ultimately reducing duplication and enhancing maintainability.

## Tasks

Modal Context
- [ ] create a ModalContext using createContext
- [ ] create a useModal function that will call useContext with the ModalContext
- [ ] create a ModalProvider (props children) 
   - [ ] including a useState hook for modal visibilaty one for modal Content
   - [ ] a function to show modal
   - [ ] a function to hide modal
   - [ ] returning the modalContext Provider
      - [ ]  with states and functions as value
      - [ ] and children inside

- [ ] wrap _app return in ModalProvider

Modal component
- [ ] import useModal
- [ ] create Modal component 
  - [ ] Gettig isVisible, modalContent, hideModal form useModal
  - [ ] return nothing if modal is not visible
  - [ ] return modal elements if visible

- [ ] Add Modal component in _app.js
- [ ] Add show modal function to on click event listeners
   - [ ] in delte button
