### ISSUE TITLE
US - Create User Accounts

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#88]
## Value proposition
As a User
I want to create an account
In order to save, edit and create events and like, edit and create comments

## Description
- Scribble / design or text
- Precise, no unnecessary information

## Acceptance criteria
- [ ] There is a Register/Login Button
- [ ] Clicking the Button when not re Button shows login Modal with a link to the Github OAuth Page
- [ ] Signing in creates
- [ ] App design matches our design criteria

## Tasks
- [ ] Create new branch USx-userStorieName
- [ ] Style new elements according our styling criteria
- [ ]
