### ISSUE TITLE
US - Style Github Sign in Modal

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#89]
## Value proposition
As a User
I want the apps design to be visually consistent
so I have an amazing user experience and never want to leave the app in my whole entire life

## Description
- Scribble / design or text
- Precise, no unnecessary information

## Acceptance criteria
- [ ] App design matches our design criteria

## Tasks
- [ ] Create new branch US_style-sign-in-modal
- [ ] research how to style NextAuth built in components
- [ ] Style components according our styling criteria
