### ISSUE TITLE
US2 - Event List

### ISSUE THREAD

**Issue by MareikeFla** [MareikeFla/community-app#9]
## Value proposition
As a user, I want a list of events 
so that I can easily browse through upcoming events 
and decide which ones might interest me.

## Description
![Image](https://github.com/MareikeFla/community-app/assets/86231054/1999d54f-3050-475b-a114-82761b6645ab)

## Acceptance criteria
- [x] Each event is shown in an individual card.
- [x] The cards are shown as a list
- [x] Every card has to show title, start date, end date, start time, end time, and place ("online" if city is empty) of the event
- [x] The list scrolls vertically
- [x] The design fits our standard criteria 

## Tasks
- [x] Create branch "US2_event-list"
- [x] Create lib/events.js
   - [x] Create mock array events for development purposes
   - [x] create object on it including keys title, dateStart, dateEnde, timeStart, timeEnd, city, id
- [x] Create EventPreview (props: event) component and return  
   - [x] Title 
   - [x] date
   - [x] time
   - [x] city (or “online” if city is empty)
 of the event.
- [x] Create a EventList Component (props: array with events)
  - [x] the List component renders a ul Element
  - [x] it maps over the array, creating an li element with the EventPreview component for each item in the array
  - [x]  the li element gets the event id as key
  - [x] the EventPreview Components get the event as prop

index.js
- [x] add the List Component
- [x] give the event array as prop to the List component

**Comment by MerleMak** [comment]
Great job! 
I love the look also!

If you switch the order (this being the first US and the layout being the second) i will be very happy :)
