### ISSUE TITLE
US - Restrict Event Creation To Logged In Users

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#90]
## Value proposition
As a Page Admin
I only want logged in users to be able to create events
In order to provide content moderation to my page

## Description
- Scribble / design or text
- Precise, no unnecessary information

## Acceptance criteria
- [x] Create Event page is only accesible to logged in users
- [x] if user is not logged in, show a page motivating users to log in
- [x] App design matches our design criteria

## Tasks
- [ ] Create new branch US_restrict-event-creation
- [ ] In EventFormContainer, check if user is logged in
- [ ] if not logged in, render MessageCard component with a prompt to log in
- [ ] if logged in Event form is shown
- [ ] Style new elements according our styling criteria
