### ISSUE TITLE
US - Restrict Delete And Edit Events To Logged In Event Owners

### ISSUE THREAD

**Issue by Bruno0221** [MareikeFla/community-app#91]
## Value proposition
As a User
I want to be able to edit and delete the events I created
In order to react to changes

## Description
- Scribble / design or text
- Precise, no unnecessary information

## Acceptance criteria
- [ ] Edit and Delete button on EventDetails Page is only visible if user currently logged in created this event

## Tasks
- [ ] Create new branch US_restrict-edit-and-delete
- [ ] on event creation, save user id in event
- [ ] add createdBy key to Event schema

- [ ] in EventDetail component, conditionally render edit and delete button component to 
- [ ] Style new elements according our styling criteria

**Comment by alex96dev** [comment]
LGTM!

Take in consideration adding a description and wireframe.

**Comment by Bruno0221** [comment]
Thanks for the feedback. We thought we could omit the wireframe as we are just hiding stuff
