### ISSUE TITLE
FIX: Events with one missing entry in the location are shown as online in the preview

### ISSUE THREAD

**Issue by MareikeFla** [MareikeFla/community-app#99]
## Value proposition

As a developer, I want my code to be understandable and plausible
so that it can be easily reused and maintained.

## Description

Because of brains does wired things sometime, we have accidentally switched the colors for primary and secondary buttons. So you can color a primary button by adding secondary color, which may sound fun but is sometimes a bit confusing.

## Acceptance criteria

- [ ] using primary button color for primary buttons and secondary button color for secondary buttons.

## Tasks

- [ ] create branch DS_Fix_button-colors
- [ ] Identify the spot where things went wrong
- [ ] switching colors
- [ ] make sure all buttons are displayed correct
